//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projdotnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class panier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public panier()
        {
            this.commanderProduit = new HashSet<commanderProduit>();
        }
    
        public int idpanier { get; set; }
        public int idclient { get; set; }
        public Nullable<int> qte_prod { get; set; }
        public string ref_produit { get; set; }
        public string urlproduit { get; set; }
        public Nullable<double> prix { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commanderProduit> commanderProduit { get; set; }
    }
}
